name: Java App CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: its-kapil/reusable-templates/ci-cd/github-actions/workflows/build.yml@main
    with:
      language: java
      working-directory: app
